In [1]:
import numpy as np
import pandas as pd
from yaml import safe_load
import os
from tqdm import tqdm

In [2]:
filenames = []
directory = r'D:\CRIC\cricket_score_pred-main\data' # Absolute path to the data directory. 

# Loop through the directory to get filenames
for file in os.listdir(directory):
    file_path = os.path.join(directory, file) # Join the file and directory to get full path 
    filenames.append(file_path)

In [ ]:
# Print the list of filenames to check
print(filenames)

In [ ]:
#final_df = pd.DataFrame()
#counter = 1
# for file in tqdm(filenames):
#     with open(file, 'r') as f:
#         df = pd.json_normalize(safe_load(f))
#         df['match_id'] = counter
#         final_df = final_df.append(df)
#         counter+=1
# final_df

# using append() inside a loop can be inefficient because it creates a new DataFrame each time. #To optimize it, store the Df in a list and concatenate them at the end using pd.concat()

In [3]:
final_df = []  # Using a list to accumulate dataframes
counter = 1

for file in tqdm(filenames):
    with open(file, 'r') as f:
        #load the yaml file and normalise the JSON Content
        df=pd.json_normalize(safe_load(f))
        # Add Match_id column
        df['match_id'] = counter
        # Append Dataframe to the list
        final_df.append(df)
        counter +=1
        
# Concatenate all data frames in the list into a single data frame

final_df = pd.concat(final_df, ignore_index= True) 

# display final Dataframe

final_df

100%|██████████| 776/776 [02:03<00:00,  6.29it/s]

,innings,meta.data_version,meta.created,meta.revision,info.dates,info.gender,info.match_type,info.outcome.by.wickets,info.outcome.winner,info.overs,...,info.outcome.by.runs,info.match_type_number,info.neutral_venue,info.outcome.method,info.outcome.result,info.outcome.eliminator,info.supersubs.New Zealand,info.supersubs.South Africa,info.bowl_out,info.outcome.bowl_out
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-18,2,[2017-02-17],male,T20,5.0,Sri Lanka,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-19,2,[2017-02-19],male,T20,2.0,Sri Lanka,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-23,1,[2017-02-22],male,T20,NaN,Australia,20,...,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",0.9,2016-09-12,1,[2016-09-05],male,T20,NaN,Hong Kong,20,...,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",0.9,2016-06-19,1,[2016-06-18],male,T20,NaN,Zimbabwe,20,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,"[{'1st innings': {'team': 'West Indies', 'deli...",0.9,2013-02-18,1,[2007-09-11],male,T20,8.0,South Africa,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
772,"[{'1st innings': {'team': 'Kenya', 'deliveries...",0.9,2013-02-18,1,[2007-09-12],male,T20,9.0,New Zealand,20,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
773,"[{'1st innings': {'team': 'Pakistan', 'deliver...",0.9,2013-02-18,1,[2007-09-12],male,T20,NaN,Pakistan,20,...,51.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
774,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2013-02-18,1,[2007-09-12],male,T20,5.0,Zimbabwe,20,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
775,"[{'1st innings': {'team': 'West Indies', 'deli...",0.9,2013-02-18,1,[2007-09-13],male,T20,6.0,Bangladesh,20,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
backup = final_df.copy()

In [5]:
final_df.copy

<bound method NDFrame.copy of                                                innings  meta.data_version  \
0    [{'1st innings': {'team': 'Australia', 'delive...                0.9
1    [{'1st innings': {'team': 'Australia', 'delive...                0.9
2    [{'1st innings': {'team': 'Australia', 'delive...                0.9
3    [{'1st innings': {'team': 'Hong Kong', 'delive...                0.9
4    [{'1st innings': {'team': 'Zimbabwe', 'deliver...                0.9
..                                                 ...                ...
771  [{'1st innings': {'team': 'West Indies', 'deli...                0.9
772  [{'1st innings': {'team': 'Kenya', 'deliveries...                0.9
773  [{'1st innings': {'team': 'Pakistan', 'deliver...                0.9
774  [{'1st innings': {'team': 'Australia', 'delive...                0.9
775  [{'1st innings': {'team': 'West Indies', 'deli...                0.9

    meta.created  meta.revision    info.dates info.gender info.match_type  \
0     2017-02-18              2  [2017-02-17]        male             T20
1     2017-02-19              2  [2017-02-19]        male             T20
2     2017-02-23              1  [2017-02-22]        male             T20
3     2016-09-12              1  [2016-09-05]        male             T20
4     2016-06-19              1  [2016-06-18]        male             T20
..           ...            ...           ...         ...             ...
771   2013-02-18              1  [2007-09-11]        male             T20
772   2013-02-18              1  [2007-09-12]        male             T20
773   2013-02-18              1  [2007-09-12]        male             T20
774   2013-02-18              1  [2007-09-12]        male             T20
775   2013-02-18              1  [2007-09-13]        male             T20

     info.outcome.by.wickets info.outcome.winner  info.overs  ...  \
0                        5.0           Sri Lanka          20  ...
1                        2.0           Sri Lanka          20  ...
2                        NaN           Australia          20  ...
3                        NaN           Hong Kong          20  ...
4                        NaN            Zimbabwe          20  ...
..                       ...                 ...         ...  ...
771                      8.0        South Africa          20  ...
772                      9.0         New Zealand          20  ...
773                      NaN            Pakistan          20  ...
774                      5.0            Zimbabwe          20  ...
775                      6.0          Bangladesh          20  ...

    info.outcome.by.runs info.match_type_number info.neutral_venue  \
0                    NaN                    NaN                NaN
1                    NaN                    NaN                NaN
2                   41.0                    NaN                NaN
3                   40.0                    NaN                NaN
4                    2.0                    NaN                NaN
..                   ...                    ...                ...
771                  NaN                    NaN                NaN
772                  NaN                    NaN                1.0
773                 51.0                    NaN                1.0
774                  NaN                    NaN                1.0
775                  NaN                    NaN                1.0

    info.outcome.method info.outcome.result info.outcome.eliminator  \
0                   NaN                 NaN                     NaN
1                   NaN                 NaN                     NaN
2                   NaN                 NaN                     NaN
3                   NaN                 NaN                     NaN
4                   NaN                 NaN                     NaN
..                  ...                 ...                     ...
771                 NaN                 NaN                     NaN
772                 NaN                 NaN                     NaN
773                 NaN                 NaN                     NaN
774                 NaN                 NaN                     NaN
775                 NaN                 NaN                     NaN

     info.supersubs.New Zealand info.supersubs.South Africa  info.bowl_out  \
0                           NaN                         NaN            NaN
1                           NaN                         NaN            NaN
2                           NaN                         NaN            NaN
3                           NaN                         NaN            NaN
4                           NaN                         NaN            NaN
..                          ...                         ...            ...
771                         NaN                         NaN            NaN
772                         NaN                         NaN            NaN
773                         NaN                         NaN            NaN
774                         NaN                         NaN            NaN
775                         NaN                         NaN            NaN

     info.outcome.bowl_out
0                      NaN
1                      NaN
2                      NaN
3                      NaN
4                      NaN
..                     ...
771                    NaN
772                    NaN
773                    NaN
774                    NaN
775                    NaN

[776 rows x 28 columns]>

In [6]:
final_df.drop(columns=[
    'meta.data_version',
    'meta.created',
    'meta.revision',
    'info.outcome.bowl_out',
    'info.bowl_out',
    'info.supersubs.South Africa',
    'info.supersubs.New Zealand',
    'info.outcome.eliminator',
    'info.outcome.result',
    'info.outcome.method',
    'info.neutral_venue',
    'info.match_type_number',
    'info.outcome.by.runs',
    'info.outcome.by.wickets'
],inplace=True)

In [7]:
final_df

,innings,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,match_id,info.city
0,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-17],male,T20,Sri Lanka,20,[DAS Gunaratne],"[Australia, Sri Lanka]",field,Sri Lanka,"[MD Martell, P Wilson]",Melbourne Cricket Ground,1,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-19],male,T20,Sri Lanka,20,[DAS Gunaratne],"[Australia, Sri Lanka]",field,Sri Lanka,"[SD Fry, SJ Nogajski]","Simonds Stadium, South Geelong",2,Victoria
2,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-22],male,T20,Australia,20,[A Zampa],"[Australia, Sri Lanka]",field,Sri Lanka,"[MD Martell, P Wilson]",Adelaide Oval,3,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",[2016-09-05],male,T20,Hong Kong,20,NaN,"[Ireland, Hong Kong]",bat,Hong Kong,"[R Black, AJ Neill]","Bready Cricket Club, Magheramason",4,Londonderry
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",[2016-06-18],male,T20,Zimbabwe,20,[E Chigumbura],"[Zimbabwe, India]",field,India,"[TJ Matibiri, RB Tiffin]",Harare Sports Club,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,"[{'1st innings': {'team': 'West Indies', 'deli...",[2007-09-11],male,T20,South Africa,20,[CH Gayle],"[South Africa, West Indies]",field,South Africa,"[MR Benson, DJ Harper]",New Wanderers Stadium,772,Johannesburg
772,"[{'1st innings': {'team': 'Kenya', 'deliveries...",[2007-09-12],male,T20,New Zealand,20,[MR Gillespie],"[Kenya, New Zealand]",field,New Zealand,"[BR Doctrove, SJA Taufel]",Kingsmead,773,Durban
773,"[{'1st innings': {'team': 'Pakistan', 'deliver...",[2007-09-12],male,T20,Pakistan,20,[Shahid Afridi],"[Pakistan, Scotland]",field,Scotland,"[SJ Davis, SJA Taufel]",Kingsmead,774,Durban
774,"[{'1st innings': {'team': 'Australia', 'delive...",[2007-09-12],male,T20,Zimbabwe,20,[BRM Taylor],"[Australia, Zimbabwe]",bat,Australia,"[Asad Rauf, AL Hill]",Newlands,775,Cape Town
775,"[{'1st innings': {'team': 'West Indies', 'deli...",[2007-09-13],male,T20,Bangladesh,20,[Mohammad Ashraful],"[Bangladesh, West Indies]",field,Bangladesh,"[MR Benson, NJ Llong]",New Wanderers Stadium,776,Johannesburg

In [8]:
final_df['info.gender'].value_counts()

male      462
female    314
Name: info.gender, dtype: int64

In [9]:
final_df = final_df[final_df['info.gender'] == 'male']
final_df = final_df.drop(columns=['info.gender'])
final_df

,innings,info.dates,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,match_id,info.city
0,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-17],T20,Sri Lanka,20,[DAS Gunaratne],"[Australia, Sri Lanka]",field,Sri Lanka,"[MD Martell, P Wilson]",Melbourne Cricket Ground,1,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-19],T20,Sri Lanka,20,[DAS Gunaratne],"[Australia, Sri Lanka]",field,Sri Lanka,"[SD Fry, SJ Nogajski]","Simonds Stadium, South Geelong",2,Victoria
2,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-22],T20,Australia,20,[A Zampa],"[Australia, Sri Lanka]",field,Sri Lanka,"[MD Martell, P Wilson]",Adelaide Oval,3,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",[2016-09-05],T20,Hong Kong,20,NaN,"[Ireland, Hong Kong]",bat,Hong Kong,"[R Black, AJ Neill]","Bready Cricket Club, Magheramason",4,Londonderry
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",[2016-06-18],T20,Zimbabwe,20,[E Chigumbura],"[Zimbabwe, India]",field,India,"[TJ Matibiri, RB Tiffin]",Harare Sports Club,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,"[{'1st innings': {'team': 'West Indies', 'deli...",[2007-09-11],T20,South Africa,20,[CH Gayle],"[South Africa, West Indies]",field,South Africa,"[MR Benson, DJ Harper]",New Wanderers Stadium,772,Johannesburg
772,"[{'1st innings': {'team': 'Kenya', 'deliveries...",[2007-09-12],T20,New Zealand,20,[MR Gillespie],"[Kenya, New Zealand]",field,New Zealand,"[BR Doctrove, SJA Taufel]",Kingsmead,773,Durban
773,"[{'1st innings': {'team': 'Pakistan', 'deliver...",[2007-09-12],T20,Pakistan,20,[Shahid Afridi],"[Pakistan, Scotland]",field,Scotland,"[SJ Davis, SJA Taufel]",Kingsmead,774,Durban
774,"[{'1st innings': {'team': 'Australia', 'delive...",[2007-09-12],T20,Zimbabwe,20,[BRM Taylor],"[Australia, Zimbabwe]",bat,Australia,"[Asad Rauf, AL Hill]",Newlands,775,Cape Town
775,"[{'1st innings': {'team': 'West Indies', 'deli...",[2007-09-13],T20,Bangladesh,20,[Mohammad Ashraful],"[Bangladesh, West Indies]",field,Bangladesh,"[MR Benson, NJ Llong]",New Wanderers Stadium,776,Johannesburg

In [10]:
final_df['info.match_type'].value_counts()

T20    462
Name: info.match_type, dtype: int64

In [11]:
final_df['info.overs'].value_counts()

20    460
50      2
Name: info.overs, dtype: int64

In [12]:
final_df = final_df[final_df['info.overs'] == 20]
final_df.drop(columns=['info.overs','info.match_type'])
final_df

,innings,info.dates,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,match_id,info.city
0,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-17],T20,Sri Lanka,20,[DAS Gunaratne],"[Australia, Sri Lanka]",field,Sri Lanka,"[MD Martell, P Wilson]",Melbourne Cricket Ground,1,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-19],T20,Sri Lanka,20,[DAS Gunaratne],"[Australia, Sri Lanka]",field,Sri Lanka,"[SD Fry, SJ Nogajski]","Simonds Stadium, South Geelong",2,Victoria
2,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-22],T20,Australia,20,[A Zampa],"[Australia, Sri Lanka]",field,Sri Lanka,"[MD Martell, P Wilson]",Adelaide Oval,3,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",[2016-09-05],T20,Hong Kong,20,NaN,"[Ireland, Hong Kong]",bat,Hong Kong,"[R Black, AJ Neill]","Bready Cricket Club, Magheramason",4,Londonderry
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",[2016-06-18],T20,Zimbabwe,20,[E Chigumbura],"[Zimbabwe, India]",field,India,"[TJ Matibiri, RB Tiffin]",Harare Sports Club,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,"[{'1st innings': {'team': 'West Indies', 'deli...",[2007-09-11],T20,South Africa,20,[CH Gayle],"[South Africa, West Indies]",field,South Africa,"[MR Benson, DJ Harper]",New Wanderers Stadium,772,Johannesburg
772,"[{'1st innings': {'team': 'Kenya', 'deliveries...",[2007-09-12],T20,New Zealand,20,[MR Gillespie],"[Kenya, New Zealand]",field,New Zealand,"[BR Doctrove, SJA Taufel]",Kingsmead,773,Durban
773,"[{'1st innings': {'team': 'Pakistan', 'deliver...",[2007-09-12],T20,Pakistan,20,[Shahid Afridi],"[Pakistan, Scotland]",field,Scotland,"[SJ Davis, SJA Taufel]",Kingsmead,774,Durban
774,"[{'1st innings': {'team': 'Australia', 'delive...",[2007-09-12],T20,Zimbabwe,20,[BRM Taylor],"[Australia, Zimbabwe]",bat,Australia,"[Asad Rauf, AL Hill]",Newlands,775,Cape Town
775,"[{'1st innings': {'team': 'West Indies', 'deli...",[2007-09-13],T20,Bangladesh,20,[Mohammad Ashraful],"[Bangladesh, West Indies]",field,Bangladesh,"[MR Benson, NJ Llong]",New Wanderers Stadium,776,Johannesburg

In [ ]:
final_df.iloc[0]['innings'][0]['1st innings']['deliveries']

In [14]:
import pickle
pickle.dump(final_df, open('dataset_level1.pk1', 'wb'))

In [17]:
matches = pickle.load(open('dataset_level1.pk1','rb'))
matches

,innings,info.dates,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,match_id,info.city
0,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-17],T20,Sri Lanka,20,[DAS Gunaratne],"[Australia, Sri Lanka]",field,Sri Lanka,"[MD Martell, P Wilson]",Melbourne Cricket Ground,1,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-19],T20,Sri Lanka,20,[DAS Gunaratne],"[Australia, Sri Lanka]",field,Sri Lanka,"[SD Fry, SJ Nogajski]","Simonds Stadium, South Geelong",2,Victoria
2,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-22],T20,Australia,20,[A Zampa],"[Australia, Sri Lanka]",field,Sri Lanka,"[MD Martell, P Wilson]",Adelaide Oval,3,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",[2016-09-05],T20,Hong Kong,20,NaN,"[Ireland, Hong Kong]",bat,Hong Kong,"[R Black, AJ Neill]","Bready Cricket Club, Magheramason",4,Londonderry
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",[2016-06-18],T20,Zimbabwe,20,[E Chigumbura],"[Zimbabwe, India]",field,India,"[TJ Matibiri, RB Tiffin]",Harare Sports Club,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,"[{'1st innings': {'team': 'West Indies', 'deli...",[2007-09-11],T20,South Africa,20,[CH Gayle],"[South Africa, West Indies]",field,South Africa,"[MR Benson, DJ Harper]",New Wanderers Stadium,772,Johannesburg
772,"[{'1st innings': {'team': 'Kenya', 'deliveries...",[2007-09-12],T20,New Zealand,20,[MR Gillespie],"[Kenya, New Zealand]",field,New Zealand,"[BR Doctrove, SJA Taufel]",Kingsmead,773,Durban
773,"[{'1st innings': {'team': 'Pakistan', 'deliver...",[2007-09-12],T20,Pakistan,20,[Shahid Afridi],"[Pakistan, Scotland]",field,Scotland,"[SJ Davis, SJA Taufel]",Kingsmead,774,Durban
774,"[{'1st innings': {'team': 'Australia', 'delive...",[2007-09-12],T20,Zimbabwe,20,[BRM Taylor],"[Australia, Zimbabwe]",bat,Australia,"[Asad Rauf, AL Hill]",Newlands,775,Cape Town
775,"[{'1st innings': {'team': 'West Indies', 'deli...",[2007-09-13],T20,Bangladesh,20,[Mohammad Ashraful],"[Bangladesh, West Indies]",field,Bangladesh,"[MR Benson, NJ Llong]",New Wanderers Stadium,776,Johannesburg

In [21]:
matches.iloc[0]

innings                 [{'1st innings': {'team': 'Australia', 'delive...
info.dates                                                   [2017-02-17]
info.match_type                                                       T20
info.outcome.winner                                             Sri Lanka
info.overs                                                             20
info.player_of_match                                      [DAS Gunaratne]
info.teams                                         [Australia, Sri Lanka]
info.toss.decision                                                  field
info.toss.winner                                                Sri Lanka
info.umpires                                       [MD Martell, P Wilson]
info.venue                                       Melbourne Cricket Ground
match_id                                                                1
info.city                                                             NaN
Name: 0, dtype: object

In [40]:
matches.iloc[0]['innings'][0]['1st innings']['deliveries']

[{0.1: {'batsman': 'AJ Finch',
   'bowler': 'SL Malinga',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.2: {'batsman': 'AJ Finch',
   'bowler': 'SL Malinga',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.3: {'batsman': 'AJ Finch',
   'bowler': 'SL Malinga',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {0.4: {'batsman': 'M Klinger',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {0.5: {'batsman': 'M Klinger',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.6: {'batsman': 'M Klinger',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {1.1: {'batsman': 'M Klinger',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.2: {'batsman': 'M Klinger',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {1.3: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.4: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.5: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {1.6: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {2.1: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.2: {'batsman': 'AJ Finch',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.3: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.4: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.5: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {2.6: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.1: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.2: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.3: {'batsman': 'M Klinger',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.4: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.5: {'batsman': 'M Klinger',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {3.6: {'batsman': 'M Klinger',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {4.1: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {4.2: {'batsman': 'AJ Finch',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {4.3: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {4.4: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {4.5: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {4.6: {'batsman': 'AJ Finch',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.1: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.2: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'extras': {'wides': 1},
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {5.3: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.4: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.5: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.6: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.7: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {6.1: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.2: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.3: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {6.4: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.5: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.6: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {7.1: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {7.2: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.3: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.4: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'extras': {'byes': 1},
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {7.5: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {7.6: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.1: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.2: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {8.3: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.4: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.5: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.6: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.1: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.2: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {9.3: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {9.4: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {9.5: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {9.6: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {10.1: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.2: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'extras': {'legbyes': 1},
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {10.3: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['SL Malinga'],
    'kind': 'caught',
    'player_out': 'M Klinger'}}},
 {10.4: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {10.5: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.6: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {11.1: {'batsman': 'AJ Finch',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'TM Head',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {11.2: {'batsman': 'AJ Finch',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'TM Head',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {11.3: {'batsman': 'AJ Finch',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'TM Head',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['SL Malinga'],
    'kind': 'caught',
    'player_out': 'AJ Finch'}}},
 {11.4: {'batsman': 'TM Head',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.5: {'batsman': 'MC Henriques',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.6: {'batsman': 'TM Head',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.1: {'batsman': 'TM Head',
   'bowler': 'S Prasanna',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {12.2: {'batsman': 'TM Head',
   'bowler': 'S Prasanna',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.3: {'batsman': 'MC Henriques',
   'bowler': 'S Prasanna',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.4: {'batsman': 'TM Head',
   'bowler': 'S Prasanna',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {12.5: {'batsman': 'TM Head',
   'bowler': 'S Prasanna',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.6: {'batsman': 'MC Henriques',
   'bowler': 'S Prasanna',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.1: {'batsman': 'MC Henriques',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {13.2: {'batsman': 'MC Henriques',
   'bowler': 'SL Malinga',
   'extras': {'wides': 1},
   'non_striker': 'TM Head',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {13.3: {'batsman': 'MC Henriques',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.4: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {13.5: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.6: {'batsman': 'MC Henriques',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.7: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.1: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.2: {'batsman': 'MC Henriques',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'TM Head',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {14.3: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.4: {'batsman': 'MC Henriques',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'TM Head',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {14.5: {'batsman': 'MC Henriques',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'TM Head',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {14.6: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {15.1: {'batsman': 'MC Henriques',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'TM Head',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['CK Kapugedera'],
    'kind': 'caught',
    'player_out': 'MC Henriques'}}},
 {15.2: {'batsman': 'TM Head',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.3: {'batsman': 'AJ Turner',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'TM Head',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {15.4: {'batsman': 'AJ Turner',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.5: {'batsman': 'TM Head',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {15.6: {'batsman': 'TM Head',
   'bowler': 'JRMVB Sanjaya',
   'extras': {'wides': 1},
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {15.7: {'batsman': 'TM Head',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {16.1: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {16.2: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {16.3: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.4: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.5: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.6: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.1: {'batsman': 'TM Head',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.2: {'batsman': 'AJ Turner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TM Head',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {17.3: {'batsman': 'AJ Turner',
   'bowler': 'KMDN Kulasekara',
   'extras': {'noballs': 1},
   'non_striker': 'TM Head',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {17.4: {'batsman': 'AJ Turner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.5: {'batsman': 'TM Head',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.6: {'batsman': 'AJ Turner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.7: {'batsman': 'TM Head',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {18.1: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {18.2: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {18.3: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {18.4: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['S Prasanna'],
    'kind': 'caught',
    'player_out': 'TM Head'}}},
 {18.5: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'JP Faulkner',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['S Prasanna'],
    'kind': 'caught',
    'player_out': 'AJ Turner'}}},
 {18.6: {'batsman': 'JP Faulkner',
   'bowler': 'SL Malinga',
   'non_striker': 'TD Paine',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.1: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TD Paine',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {19.2: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TD Paine',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {19.3: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TD Paine',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {19.4: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'extras': {'wides': 1},
   'non_striker': 'TD Paine',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {19.5: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TD Paine',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1},
   'wicket': {'fielders': ['CK Kapugedera', 'KMDN Kulasekara'],
    'kind': 'run out',
    'player_out': 'TD Paine'}}},
 {19.6: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'PJ Cummins',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {19.7: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'PJ Cummins',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}}]

In [28]:
matches.to_excel('t20_matches.xlsx',index = True)

In [ ]:
# # List of match IDs being skipped
# skipped_match_ids = [75, 108, 150, 180, 268, 360, 443, 458, 584, 748, 982, 1052, 1111, 1226, 1345]

# # Filter the DataFrame for skipped matches
# skipped_matches = matches.loc[matches.index.isin(skipped_match_ids)]

# # Display the skipped matches
# print(skipped_matches)

# # Or, for a more detailed view, iterate through and inspect each skipped match
# for match_id in skipped_match_ids:
#     print(f"Match ID: {match_id}")
#     print(matches.loc[match_id])
#     print("\n" + "-"*50 + "\n")

In [42]:
import pandas as pd

# Initialize the main DataFrame to store ball-by-ball data for 1st innings of each match
count = 1  # Keeps track of match number or match_id
Main_df = pd.DataFrame()

# Loop through each row of final_df, which contains info about matches
# Each row in final_df represents data for one match
for index, row in final_df.iterrows():

    # Initialize empty lists to store ball-by-ball details for the current match
    ball_of_match = []  # List to store ball numbers
    batsman = []        # List to store batsman names
    bowler = []         # List to store bowler names
    runs = []           # List to store runs scored on each ball
    player_of_dismissed = []  # List to store the player dismissed on each ball (if any)
    teams = []          # List to store team names
    batting_team = []   # List to store the batting team
    match_id = []       # List to store the match id
    city = []           # List to store the city where the match was played
    venue = []          # List to store the venue name

    # Iterate over each delivery in the 1st innings
    for ball in row['innings'][0]['1st innings']['deliveries']:
        # For each ball in the delivery, extract details
        for key in ball.keys():  # ball keys represent the ball number, e.g., '0.1', '0.2'
            match_id.append(count)  # Append the match id (current match number)
            batting_team.append(row['innings'][0]['1st innings']['team'])  # Append the batting team
            teams.append(row['info.teams'])  # Append both teams playing in the match
            ball_of_match.append(key)  # Append the ball number (e.g., '0.1', '0.2')
            batsman.append(ball[key]['batsman'])  # Append batsman name for this ball
            bowler.append(ball[key]['bowler'])  # Append bowler name for this ball
            runs.append(ball[key]['runs']['total'])  # Append runs scored on this ball
            city.append(row['info.city'])  # Append the city where the match was played
            venue.append(row['info.venue'])  # Append the venue where the match was played

            try:
                # Try to get the player dismissed on this ball, if any
                player_of_dismissed.append(ball[key]['wicket']['player_out'])
            except:
                # If no player was dismissed, append '0' to the list
                player_of_dismissed.append('0')

    # Create a temporary DataFrame (loop_df) for the current match's ball-by-ball data
    loop_df = pd.DataFrame({
        'match_id': match_id,
        'teams': teams,
        'batting_team': batting_team,
        'ball': ball_of_match,
        'batsman': batsman,
        'bowler': bowler,
        'runs': runs,
        'player_dismissed': player_of_dismissed,
        'city': city,
        'venue': venue
    })

    # Instead of append(), use pandas.concat to combine the current loop_df with Main_df
    Main_df = pd.concat([Main_df, loop_df], ignore_index=True)

    # Increment the match count for the next match
    count += 1

# The final Main_df now contains ball-by-ball data for all the matches in final_df's first innings.

In [43]:
Main_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue
0,1,"[Australia, Sri Lanka]",Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground
1,1,"[Australia, Sri Lanka]",Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground
2,1,"[Australia, Sri Lanka]",Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground
3,1,"[Australia, Sri Lanka]",Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground
4,1,"[Australia, Sri Lanka]",Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...,...,...
55749,460,"[Bangladesh, West Indies]",West Indies,19.2,DJ Bravo,Shakib Al Hasan,2,0,Johannesburg,New Wanderers Stadium
55750,460,"[Bangladesh, West Indies]",West Indies,19.3,DJ Bravo,Shakib Al Hasan,0,DJ Bravo,Johannesburg,New Wanderers Stadium
55751,460,"[Bangladesh, West Indies]",West Indies,19.4,DBL Powell,Shakib Al Hasan,1,0,Johannesburg,New Wanderers Stadium
55752,460,"[Bangladesh, West Indies]",West Indies,19.5,DR Smith,Shakib Al Hasan,6,0,Johannesburg,New Wanderers Stadium
55753,460,"[Bangladesh, West Indies]",West Indies,19.6,DR Smith,Shakib Al Hasan,0,DR Smith,Johannesburg,New Wanderers Stadium

In [44]:
def bowl(row):
    for team in row['teams']:
        if team != row['batting_team']:
            return team

In [45]:
Main_df['bowling_team'] = Main_df.apply(bowl,axis=1)

In [46]:
Main_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,1,"[Australia, Sri Lanka]",Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
1,1,"[Australia, Sri Lanka]",Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
2,1,"[Australia, Sri Lanka]",Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,Sri Lanka
3,1,"[Australia, Sri Lanka]",Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,Sri Lanka
4,1,"[Australia, Sri Lanka]",Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
...,...,...,...,...,...,...,...,...,...,...,...
55749,460,"[Bangladesh, West Indies]",West Indies,19.2,DJ Bravo,Shakib Al Hasan,2,0,Johannesburg,New Wanderers Stadium,Bangladesh
55750,460,"[Bangladesh, West Indies]",West Indies,19.3,DJ Bravo,Shakib Al Hasan,0,DJ Bravo,Johannesburg,New Wanderers Stadium,Bangladesh
55751,460,"[Bangladesh, West Indies]",West Indies,19.4,DBL Powell,Shakib Al Hasan,1,0,Johannesburg,New Wanderers Stadium,Bangladesh
55752,460,"[Bangladesh, West Indies]",West Indies,19.5,DR Smith,Shakib Al Hasan,6,0,Johannesburg,New Wanderers Stadium,Bangladesh
55753,460,"[Bangladesh, West Indies]",West Indies,19.6,DR Smith,Shakib Al Hasan,0,DR Smith,Johannesburg,New Wanderers Stadium,Bangladesh

In [47]:
Main_df.drop(columns=['teams'],inplace=True)

In [48]:
Main_df['batting_team'].unique()

array(['Australia', 'Hong Kong', 'Zimbabwe', 'India', 'Bangladesh',
       'New Zealand', 'South Africa', 'England', 'West Indies', 'Ireland',
       'Afghanistan', 'Pakistan', 'United Arab Emirates', 'Scotland',
       'Oman', 'Papua New Guinea', 'Sri Lanka', 'Netherlands', 'Nepal',
       'Vanuatu', 'Philippines', 'United States of America', 'Germany',
       'Ghana', 'Uganda', 'Kenya', 'Namibia', 'Nigeria', 'Botswana',
       'Guernsey', 'Denmark', 'Jersey', 'Italy', 'Norway', 'Thailand',
       'Malaysia', 'Maldives', 'Singapore', 'Kuwait', 'Bermuda', 'Canada',
       'Cayman Islands', 'Portugal', 'Gibraltar', 'Spain', 'Bhutan',
       'Qatar', 'Iran', 'Belgium', 'Isle of Man', 'Bulgaria', 'Romania'],
      dtype=object)

In [49]:
teams = [
    'Australia',
    'India',
    'Bangladesh',
    'New Zealand',
    'South Africa',
    'England',
    'West Indies',
    'Afghanistan',
    'Pakistan',
    'Sri Lanka'    
]

In [50]:
Main_df = Main_df[Main_df['batting_team'].isin(teams)]
Main_df = Main_df[Main_df['bowling_team'].isin(teams)]

In [51]:
Main_df

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,1,Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
1,1,Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
2,1,Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,Sri Lanka
3,1,Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,Sri Lanka
4,1,Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
...,...,...,...,...,...,...,...,...,...,...
55749,460,West Indies,19.2,DJ Bravo,Shakib Al Hasan,2,0,Johannesburg,New Wanderers Stadium,Bangladesh
55750,460,West Indies,19.3,DJ Bravo,Shakib Al Hasan,0,DJ Bravo,Johannesburg,New Wanderers Stadium,Bangladesh
55751,460,West Indies,19.4,DBL Powell,Shakib Al Hasan,1,0,Johannesburg,New Wanderers Stadium,Bangladesh
55752,460,West Indies,19.5,DR Smith,Shakib Al Hasan,6,0,Johannesburg,New Wanderers Stadium,Bangladesh
55753,460,West Indies,19.6,DR Smith,Shakib Al Hasan,0,DR Smith,Johannesburg,New Wanderers Stadium,Bangladesh

In [53]:
Extracted_Data = Main_df[['match_id','batting_team','bowling_team','ball','runs','player_dismissed','city','venue']]

In [54]:
Extracted_Data

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,1,Australia,Sri Lanka,0.1,0,0,NaN,Melbourne Cricket Ground
1,1,Australia,Sri Lanka,0.2,0,0,NaN,Melbourne Cricket Ground
2,1,Australia,Sri Lanka,0.3,1,0,NaN,Melbourne Cricket Ground
3,1,Australia,Sri Lanka,0.4,2,0,NaN,Melbourne Cricket Ground
4,1,Australia,Sri Lanka,0.5,0,0,NaN,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...
55749,460,West Indies,Bangladesh,19.2,2,0,Johannesburg,New Wanderers Stadium
55750,460,West Indies,Bangladesh,19.3,0,DJ Bravo,Johannesburg,New Wanderers Stadium
55751,460,West Indies,Bangladesh,19.4,1,0,Johannesburg,New Wanderers Stadium
55752,460,West Indies,Bangladesh,19.5,6,0,Johannesburg,New Wanderers Stadium
55753,460,West Indies,Bangladesh,19.6,0,DR Smith,Johannesburg,New Wanderers Stadium

In [57]:
Extracted_Data.to_csv('T20.csv')